# Topics Covered:
# NumPy
NumPy (Numerical Python) is a powerful Python library for numerical computing and working with arrays. It provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to operate on them.
## Installation:
pip install numpy
## Importing NumPy:
import numpy as np

# Array
An array is a grid of values (all of the same type) indexed by integers. NumPy arrays are faster and more efficient than Python lists.
## Types of Arrays:
 1. 1D Array (One-dimensional)
 2. 2D Array (Two-dimensional - Matrix)
 3. 3D Array (Three-dimensional)
## Creating Arrays:
 1. From Python list:
 arr = np.array([1, 2, 3, 4, 5])

 2. Array of zeros:
 zeros = np.zeros()            
 zeros_2d = np.zeros()      

 3. Array of ones:
 ones = np.ones()                
 ones_2d = np.ones()       

 4. Array with range:
 arr = np.arange(start,stop)           
 arr = np.arange(start,stop,step)        
## Array Attributes:
arr = np.array([[1, 2, 3], [4, 5, 6]])
1. ndim - number of dimensions
print(arr.ndim)                  # Output: 2
2. shape - dimensions of array
print(arr.shape)                 # Output: (2, 3)
3. size - total number of elements
print(arr.size)                  # Output: 6
4. dtype - data type of elements
print(arr.dtype)                 # Output: int64 (or int32)
   

In [23]:
import numpy as np

In [24]:
l1=[1,2,3,4]
arr=np.array(l1)

In [25]:
print(arr)

[1 2 3 4]


In [27]:
print(arr.ndim) # no of dimention
print(arr.shape) # dimention of array
print(arr.size )  # size of array
print(arr.dtype) # data type of element

1
(4,)
4
int64


In [28]:
# array of zeros
z=np.zeros(5)
print(z)
print("="*60)
z2=np.zeros((2,3))
print(z2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#array of ones
o=np.ones(5)
print(o)
print("="*60)
o2=np.ones((2,3))
print(o2)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
#array with range
a=np.arange(0,10)
print(a)
print("="*60)
a1=np.arange(0,10,3) # 0 is start, 10 is end, 3 is the steps 
print(a1)

[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]


In [31]:
# M-D array
lst1=[1,2,3,4,5,6]
lst2=[2,3,4,1,6,7]
lst3=[6,7,8,9,0,2]
ar=np.array([lst1,lst2,lst3])
print(ar)

[[1 2 3 4 5 6]
 [2 3 4 1 6 7]
 [6 7 8 9 0 2]]


In [32]:
#shape and reshape
ar.shape

(3, 6)

In [33]:
ar.reshape(6,3)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [1, 6, 7],
       [6, 7, 8],
       [9, 0, 2]])

In [34]:
ar.reshape(9,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [2, 3],
       [4, 1],
       [6, 7],
       [6, 7],
       [8, 9],
       [0, 2]])

In [35]:
ar.reshape(1,18)

array([[1, 2, 3, 4, 5, 6, 2, 3, 4, 1, 6, 7, 6, 7, 8, 9, 0, 2]])

# indexing or access

In [97]:
arr=np.array([10,20,30,40,50,60,70]) #1D array

In [99]:
print(arr[2])
# array slicing
print(arr[1:4])
print(arr[:4])
print(arr[2:])

30
[20 30 40]
[10 20 30 40]
[30 40 50 60 70]


In [40]:
arr=np.array([[1,2,3,4],[5,6,7,8]]) #2d array

In [41]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
print("print whole array")
print(arr[:])

print whole array
[[1 2 3 4]
 [5 6 7 8]]


In [79]:
print("print specific row")
print(arr[0])
print("________________________")
print(arr[1])

print specific row
[1 2 3 4]
________________________
[5 6 7 8]


In [80]:
print("print specific part of array")
print(arr[0:1,1:3])

print specific part of array
[[2 3]]


In [81]:
print(arr[0:2,0:2])

[[1 2]
 [5 6]]


In [82]:
print(arr[0:2,2:4])

[[3 4]
 [7 8]]


In [83]:
# in above example (note: index start from 0)
# 0:2 means start from 0th row index and unitl the 2nd row index
# 2:4 means start from 2nd column index until the 4th column index

# random array

In [87]:
arr=np.random.rand(3,4) # 3*4 array with random values
print(arr)

[[0.33807491 0.20004727 0.04852421 0.78506925]
 [0.22975956 0.58662945 0.15024939 0.29080529]
 [0.34529998 0.54053293 0.98722049 0.28627472]]


In [88]:
arr=np.random.randint(1,10,50)# random 50 integer between 1 to 50
print(arr)

[9 1 6 2 1 1 4 4 4 8 5 2 2 9 5 3 4 5 9 7 4 3 9 8 4 7 3 3 5 6 4 8 3 8 4 8 4
 7 7 6 9 1 5 2 1 4 3 5 5 3]


In [95]:
arr=np.random.rand(1,2,50)
print(arr)

[[[0.66435737 0.74987757 0.70162708 0.37960992 0.79737428 0.12831342
   0.08982787 0.05044432 0.89396856 0.11045715 0.22047993 0.66496098
   0.22044292 0.44432492 0.23765166 0.44770902 0.14054076 0.82424491
   0.59223201 0.5043429  0.1311881  0.09174876 0.53971815 0.7794836
   0.1042394  0.15126129 0.92582119 0.11827351 0.63700943 0.32415021
   0.59236573 0.67173694 0.2559951  0.09956471 0.11350643 0.99566317
   0.4869878  0.46381493 0.97878565 0.05969182 0.27275017 0.68161198
   0.81363707 0.2713712  0.1623464  0.50878175 0.54130128 0.05961145
   0.28773301 0.6905492 ]
  [0.98357561 0.45008607 0.95998493 0.80818315 0.24954426 0.27491655
   0.2280132  0.60035355 0.39336036 0.94957643 0.7702661  0.98343507
   0.46827656 0.09999814 0.32765643 0.26059074 0.60473233 0.07607871
   0.08952801 0.37529296 0.96596921 0.72928953 0.99129054 0.80697784
   0.08933507 0.99928583 0.3764876  0.7874816  0.32338645 0.91411627
   0.2308165  0.56738268 0.30987914 0.53573692 0.48041931 0.7037856
   0.79291

In [100]:
# linspace
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

# copy function and broadcasting

In [101]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [103]:
arr[3:6]=100
print(arr)

[  1   2   3 100 100 100   7   8   9]


In [105]:
arr[3:]=500
print(arr)

[  1   2   3 500 500 500 500 500 500]


In [107]:
ar=arr.copy()
print(ar)

[  1   2   3 500 500 500 500 500 500]


In [113]:
# arithmatic operation
l1=[1,2,3,4]
l2=[1,2,3,4]
a1=np.array(l1)
a2=np.array(l2)

print("addition=", a1+a2)
print("sub=", a1-a2)
print("mul=", a1*a2)
print("div=", a1/a2)

addition= [2 4 6 8]
sub= [0 0 0 0]
mul= [ 1  4  9 16]
div= [1. 1. 1. 1.]


In [114]:
r1=np.add(a1,a2)
r2=np.multiply(a1,a2)
r3=np.subtract(a1,a2)
r4=np.divide(a1,a2)

In [115]:
print(r1)
print(r2)
print(r3)
print(r4)

[2 4 6 8]
[ 1  4  9 16]
[0 0 0 0]
[1. 1. 1. 1.]


# statistical function 

In [124]:
l1=[1,2,3,4,5,67,7,44,324,555,43,2,55]
a=np.array(l1)
print("mean=",np.mean(a))
print("meadian=",np.median(a))
print("min=",np.min(a))
print("max=",np.max(a))
print("standard deviation=",np.std(a))
print("sum=",np.sum(a))
print("variance=",np.var(a))

mean= 85.53846153846153
meadian= 7.0
min= 1
max= 555
standard deviation= 159.1538275644113
sum= 1112
variance= 25329.940828402367
